name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Static analysis
    uses: less-action/reusables/.github/workflows/pre-commit.yaml@main
    with:
      python-version: "3.11"
