on:
  workflow_call:
    inputs:
      python-version:
        type: "string"
        required: false
        default: "3.10"

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ inputs.python-version }}
        restore-keys: ${{ runner.os }}-pip
    - name: pre-commit cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: >-
          ${{ runner.os }}
          -pre-commit
          -${{ inputs.python-version }}
          -${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-${{ inputs.python-version }}
          ${{ runner.os }}-pre-commit
    - run: python3 -m pip install --upgrade pre-commit
    - run: pre-commit run --all-files
