on:
  workflow_call:
    secrets:
      pypi_api_token:
        required: true
    inputs:
      requirements_file:
        type: string
        required: false
        default: "setup.cfg"

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles(inputs.requirements_file) }}
        restore-keys: ${{ runner.os }}-pip
    - name: Install dependencies
      run: python3 -m pip install --upgrade build
    - name: Build
      run: python3 -m build --sdist --wheel .
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_api_token }}
